FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    lm-sensors \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY templates/ templates/

CMD ["python", "app.py"]
